### ISSUE TITLE
Solus Linux

### ISSUE THREAD

**Issue by Aiyarree** [Barugon/CotA#1]
On Solus i can run the cota file and i can select my Character.
The field for selecting the log however is grayed-out and the stats and values are empty.
Log-Folder directory seems right. Manually pointing does not change the problem.
Refreshing button is of no help also.

Missing dependency for reading the log-files?

**Comment by Barugon** [comment]
Did you type "/stats" in-game?

**Comment by Aiyarree** [comment]
Sorry, missed this point - was too obvious for me.
Yes - several times. Also edited the text files at one point
so that the stats part was the only content. No difference.

**Comment by Barugon** [comment]
@Aiyarree 
Can you post one of the chat logs?

**Comment by Aiyarree** [comment]
[SotAChatLog_Siobhan O'Suileabhain_2018-01-15.txt](https://github.com/Barugon/CotA/files/1632763/SotAChatLog_Siobhan.O.Suileabhain_2018-01-15.txt)
unmodified chat log.

**Comment by Barugon** [comment]
@Aiyarree 
I found the issue and pushed a fix. Please let me know if it works for you.

**Comment by Aiyarree** [comment]
Perfectly fine, thank you!
